server:
  port: 8080
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8
    max-http-form-post-size: 10MB
    max-swallow-size: 10MB


spring:
  application:
    name: swagger2word
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5

# Swagger json url address
# etc. https://petstore.swagger.io/
swagger.url: https://petstore.swagger.io/v2/swagger.json



